-- AGT Compliance Columns
-- Sales
ALTER TABLE sales ADD COLUMN IF NOT EXISTS hash TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS prev_hash TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS is_certified BOOLEAN DEFAULT TRUE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS is_exempt BOOLEAN DEFAULT FALSE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS exemption_reason TEXT;

-- Payments (Receipts)
ALTER TABLE payments ADD COLUMN IF NOT EXISTS document_number TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS hash TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS prev_hash TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS is_certified BOOLEAN DEFAULT TRUE;

-- Accounting Invoices
ALTER TABLE contabil_faturas ADD COLUMN IF NOT EXISTS hash TEXT;
ALTER TABLE contabil_faturas ADD COLUMN IF NOT EXISTS prev_hash TEXT;
ALTER TABLE contabil_faturas ADD COLUMN IF NOT EXISTS is_certified BOOLEAN DEFAULT TRUE;
ALTER TABLE contabil_faturas ADD COLUMN IF NOT EXISTS type_prefix TEXT;
ALTER TABLE contabil_faturas ADD COLUMN IF NOT EXISTS is_exempt BOOLEAN DEFAULT FALSE;
ALTER TABLE contabil_faturas ADD COLUMN IF NOT EXISTS exemption_reason TEXT;
